services:

  nc-feedback:
    build: ./challenges/feedback
    container_name: nc-feedback
    restart: unless-stopped
    ports:
      - "9001:80"
    read_only: true
    tmpfs: ["/tmp"]
    pids_limit: 64
    mem_limit: 128m
    security_opt: ["no-new-privileges:true"]

  nc-cmdi:
    build: ./challenges/cmdi
    container_name: nc-cmdi
    restart: unless-stopped
    ports:
      - "9002:80"
    read_only: true
    tmpfs: ["/tmp", "/var/run/apache2", "/var/log/apache2", "/var/lock/apache2"]
    pids_limit: 64
    mem_limit: 128m
    security_opt: ["no-new-privileges:true"]
