services:

  web-challenge1:
    build: ./Challenge1Lann
    container_name: web-challenge1
    restart: unless-stopped
    ports:
      - "9001:80"
    read_only: true
    tmpfs: ["/tmp", "/var/run/apache2", "/var/log/apache2", "/var/lock/apache2"]
    pids_limit: 64
    mem_limit: 128m
    security_opt: ["no-new-privileges:true"]

  web-challenge2:
    build: ./Challenge2Lann
    container_name: web-challenge2
    restart: unless-stopped
    ports:
      - "9002:80"
    read_only: true
    tmpfs: ["/tmp", "/var/run/apache2", "/var/log/apache2", "/var/lock/apache2"]
    pids_limit: 64
    mem_limit: 128m
    security_opt: ["no-new-privileges:true"]

  web-challenge3:
    build: ./Challenge3Lann
    container_name: web-challenge3
    restart: unless-stopped
    ports:
      - "9003:80"
    read_only: true
    tmpfs: ["/tmp", "/var/run/apache2", "/var/log/apache2", "/var/lock/apache2"]
    pids_limit: 64
    mem_limit: 128m
    security_opt: ["no-new-privileges:true"]

  web-challenge4:
    build: ./Challenge4Lann
    container_name: web-challenge4
    restart: unless-stopped
    ports:
      - "9004:80"
    read_only: true
    tmpfs: ["/tmp", "/var/run/apache2", "/var/log/apache2", "/var/lock/apache2"]
    pids_limit: 64
    mem_limit: 128m
    security_opt: ["no-new-privileges:true"]

  web-challenge5:
    build: ./Challenge5Lann
    container_name: web-challenge5
    restart: unless-stopped
    ports:
      - "9005:80"
    read_only: true
    tmpfs: ["/tmp", "/var/run/apache2", "/var/log/apache2", "/var/lock/apache2"]
    pids_limit: 64
    mem_limit: 128m
    security_opt: ["no-new-privileges:true"]
